### ISSUE TITLE
definition is created for wrong DTO

### ISSUE THREAD

**Issue by rallister** [NSwag/NSwag#86] opened 2016-05-04 14:26 UTC
I Have a controller which extends from a base controller. Base controller defines
a Property called AgsDal of type IAgsDal

In a child controller this code:
```c#
[HttpPost]
public DumbResponse Post(DrrRequest ddr)
{
	return new DumbResponse();
}
```
definition that's created is not for DrrRequest but for the property AgsDal:

In service.paths.operations.parameters.schema: "$ref": "#/definitions/IAgsDal"

and in definitions I have an entry for IAgsDal. 

There are other properties which also included in definitions and I remove them specifically just before schema is generated. But the DrrRequest param is definitly not included under the path to Post operation.

Included packages from yesterday:
```xml
  <package id="NJsonSchema" version="2.13.5966.35759" targetFramework="net452" />
  <package id="NJsonSchema.CodeGeneration" version="2.13.5966.35760" targetFramework="net452" />
  <package id="NSwag.CodeGeneration" version="2.14.5966.37461" targetFramework="net452" />
  <package id="NSwag.Core" version="2.14.5966.37461" targetFramework="net452" />
 ```
 
There was an update today, behaviour did nto change:

```xml
  <package id="NJsonSchema" version="2.14.5967.31319" targetFramework="net452" />
  <package id="NJsonSchema.CodeGeneration" version="2.14.5967.31320" targetFramework="net452" />
  <package id="NSwag.CodeGeneration" version="2.15.5967.33136" targetFramework="net452" />
  <package id="NSwag.Core" version="2.15.5967.33136" targetFramework="net452" />
 ```

It is included in owin self hosted webapi 2.2, controllers are provided with this op:

```c#
var settings = new WebApiAssemblyToSwaggerGeneratorSettings
			{
				AssemblyPath = GetType().Assembly.Location,
				DefaultUrlTemplate = "api/{controller}"
			};

			var controllers = AllAssemblies
					.Matching("Ags.")
					.And("Ra.")
					.SelectMany(x => x.GetTypes())
					.Where(x => typeof(BaseController).IsAssignableFrom(x) && ( x.Name != "BaseController" ))
					//.Where(x => typeof(ApiController).IsAssignableFrom(x))
					.Select(x => x.Name);

			var generator = new WebApiAssemblyToSwaggerGenerator(settings);
			var service = generator.GenerateForControllers(controllers.ToList());
```

Interesting thing is that after i changed those "Posts" to be "Put" it generated a Post request anyway.
and gave it an operation name "PushKey2_set_AmpService" which differs from the others"PushKey2_Put", "PushKey2_Ggget". So I am wondering maybe it's not a bug, but a feature? in which case how would I avoid this feature? 
Thanks very much.

**Comment by rsuter** [comment] 2016-05-04 16:57
Very strange... and `PushKey2_set_AmpService` looks like it is generated for a property (`set_AmpService` is its setter...)

Can you provide a sample project where I can reproduce the problem?

**Comment by rallister** [comment] 2016-05-13 16:54
Sorry, I was not available for awhile. I'll set something up tomorow.

**Comment by rallister** [comment] 2016-05-15 23:08
Hi Rico, 
I've uploaded kind of barebone self hosted project which does not have any injections,etc. hosted on port 12348. MIddleware will generate result if it has word "swagger" in path. "WhateverController" contains a public property called "Bla" and that "Bla" was included in generated result. If this property is not made public then it (correctly) does not get included.
sample: https://github.com/rallister/nswagtest.git
result here : [swagger.zip](https://github.com/NSwag/NSwag/files/265327/swagger.zip)
Thanks for looking at it.

**Comment by rsuter** [comment] 2016-05-15 23:49
Strange, but GetRuntimeMethods() also returns property getter and setter methods... fixed in https://github.com/NSwag/NSwag/commit/fda203b18d4e7d84367f54d08901030dc2f2826b

**Comment by rsuter** [comment] 2016-05-15 23:49
v2.23

**Comment by rsuter** [comment] 2016-05-15 23:50
Please reopen issue if problem still exists. Thanks for using NSwag

**Closed by rsuter** 2016-05-15 23:50 UTC
Labels: bug
