### ISSUE TITLE
Run NSwag in xproj with MSBuild

### ISSUE THREAD

**Issue by shankartamma** [NSwag/NSwag#544] opened 2017-01-27 16:40 UTC
Hi

I have tried configuring a MSBuild Target in my .xproj file like below to generate CS classes fom JSON schema file using NSwag as per 
https://github.com/NSwag/NSwag/wiki/MSBuild

I have followed the below steps

1. Added NSwag.MSBuild package to the project references via NuGet Package manager.
2. Added the following in my .xproj file
```
<Target Name="BeforeBuild">
    <Exec Command="$(NSwagExe) jsonschema2csclient /Name:OrganizationList /Namespace:Organization /input:organization_jsonschema.json /output:MyEntities.cs" />
  </Target>
```
When I tried to build it is throwing the following error

`error MSB3073: The command " jsonschema2csclient /Name:OrganizationList /Namespace:Organization /input:organization_jsonschema.json /output:MyEntities.cs" exited with code 9009.`

Tried printing $(NSwagExe) and the value is empty. So I think the build is not able to find the nswag.exe from the local NuGet packages to execute the command.

Can anyone please help me how to fix the above issue?

Thanks,
Shankar

**Comment by fcsobel** [comment] 2017-01-27 18:25
I ran into a similar problem with the **PreBuildEvent**.  The NSwag package adds the settings for the $(NSwagExe) at the end of the project file so that they are not know when **PreBuildEvent** is executed.  

To fix edit the project file and make sure your command comes after all of the nswag settings.  Mine is at the end.  

![nswag-project](https://cloud.githubusercontent.com/assets/1021057/22382490/831cd5be-e48b-11e6-983a-27b85133c13c.png)

**Comment by rsuter** [comment] 2017-01-28 00:40
I only tested it with csproj files...

**Comment by shankartamma** [comment] 2017-01-30 09:59
Hi fcsobel,

Thanks for your reply.

Can you please send those code lines completely as I cannot configure with that image sample. 
Also when I used the below import statement in my xproj file the build process is trying to find the 'NSwag.MSBuild.targets' project inside my project directory and not in  the .nuget folder inside my user home directory.

**Comment by rsuter** [comment] 2017-01-31 23:45
Maybe you have to wait until the .NET Core with csproj tooling is available.

**Comment by fcsobel** [comment] 2017-02-01 00:08
Hey shankartamma,  

I thought your **.xproj** might have the same sequence problem that we run into when adding NSwagExe to a **.csproj** file.  Whenever we add the nuget package we need to manually adjust the ordering or the PreBuildEvent section.

I don't think the lines from my project file will be of any help but here they are:

```xml
<Import Project="..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets" Condition="Exists('..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets'))" />
  </Target>
```

**Comment by rsuter** [comment] 2017-02-02 12:11
Is this a duplicate of this? https://github.com/NSwag/NSwag/issues/558

Can you test with CI NuGet feed? https://www.myget.org/gallery/nswag-ci

**Comment by RSuter** [comment] 2017-06-15 16:19
xproj is deprecated and no longer supported...

**Closed by RSuter** 2017-06-15 16:19 UTC
Labels: bug
