### ISSUE TITLE
Angular2 TypeScript generation problem

### ISSUE THREAD

**Issue by hikalkan** [NSwag/NSwag#518] opened 2017-01-12 11:29 UTC
Hi,

I'm trying to generate angular 2 services, but having some trouble. I'm sending files as zip. Used latest version (v8.5).

It's very strange that my partner uses same version, same configuration, same input swagger json, but getting a valid result.

Problems (in ng2-proxy-invalid.ts):

* Using any instead of number, for integers.
* Using <any> in enum members.
* And the most important one, it calls ``fromJS`` of enums but there are not such methods on enums. For example, it calls IsTenantAvailableOutputState.fromJS but IsTenantAvailableOutputState has not such a method.

None of these problems exists in ng2proxy-valid.ts (generated by my partner's computer). To be sure, I copied swagger studio files from his computer but nothing changed. Can you help me to understand the difference.

Thank you in advance.

[nswag.zip](https://github.com/NSwag/NSwag/files/701498/nswag.zip)

**Comment by rsuter** [comment] 2017-01-12 11:43
On my computer, the output is valid... I think it has something to do with your locale. Is it possible that your partner uses an English operation system (and me too) and you are not?

**Comment by hikalkan** [comment] 2017-01-12 11:58
We both use English OS, Windows 10.

``IsTenantAvailableOutputState.fromJS`` seems very strange. Could you understand why it calls a method doesn't exists at all?

**Comment by rsuter** [comment] 2017-01-12 12:01
It is a problem with the locale. If i use

            CultureInfo ci = new CultureInfo("tr-TR");
            Thread.CurrentThread.CurrentCulture = ci;
            Thread.CurrentThread.CurrentUICulture = ci;
            CultureInfo.DefaultThreadCurrentCulture = ci;

Then I can reproduce your problem...

**Comment by hikalkan** [comment] 2017-01-12 12:04
Oh, I'm using English OS, but Turkish in regional settings. So, for my computer, default culture is tr-TR when running a dotnet application. You're right.
But it's very interesting that it's related to the culture? How can we solve it? Because there are many developers arround the World not using English as their OS language.

**Comment by rsuter** [comment] 2017-01-12 12:11
This test fails for me, but only with your locale: 

![image](https://cloud.githubusercontent.com/assets/2603405/21889317/a4eb10bc-d8c8-11e6-8b88-b17cf705c1e8.png)

**Comment by hikalkan** [comment] 2017-01-12 12:17
It may be related to famious Turkish "i" problem. In Turkish, PascalCase of integer is "İnteger", but not "Integer". And also, camelCase of "Integer" is "ınteger", not "integer". This can be the case.
So, can we run it for English culture? As better, it should handle it via invariant culture instead of current culture.

**Comment by rsuter** [comment] 2017-01-12 12:27
Fixed in NJS: https://github.com/NJsonSchema/NJsonSchema/commit/610bc4a9a03170eff2e57b3171a8fd1f5bcbd136

**Comment by hikalkan** [comment] 2017-01-12 12:30
Thanks a lot.

**Comment by rsuter** [comment] 2017-01-12 12:39
Ok, this should be fixed. Please try with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

If everything is fine, I'll release v8.6 today.

**Comment by rsuter** [comment] 2017-01-12 12:44
The build broke because the NJS NuGet packages are not available on the build server yet... I restarted the build

**Comment by rsuter** [comment] 2017-01-12 12:47
Ok the MSI installer is now available...

**Comment by hikalkan** [comment] 2017-01-12 12:49
Trying it...

**Comment by rsuter** [comment] 2017-01-12 12:51
BTW: The idea is to use invariant culture everywhere, but as you know, sometimes we forget to use the correct method because "it works on my machine"...

**Comment by hikalkan** [comment] 2017-01-12 12:53
Thank you very much, it worked as expected :) This was a really fast response and fix, very appreciated.
Yes, I know it :)

**Closed** 2017-01-12 12:53 UTC
Labels: bug

**Comment by rsuter** [comment] 2017-01-12 12:55
In the future maybe you should do occasional diffs between the generated code from your machine and your partner's so that we can detect more problems regarding the locale...

**Comment by hikalkan** [comment] 2017-01-12 13:02
We are using git and working on same project and sometimes I'm generating the proxy, sometimes he is. So, I will be more careful on changes after re-generation to see if it changes unintended parts.
