### ISSUE TITLE
No luck running NSwag on Ubuntu

### ISSUE THREAD

**Issue by andylowry** [NSwag/NSwag#482] opened 2016-12-17 01:15 UTC
Trying to get this set up to run on Ubuntu (14.04 LTS) Linux. (Running in a VirtualBox VM on Windows 7).

I did this:
* Followed instructions at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions to install nodejs and npm
* Ran `npm install -g nswag` and got NSwag v8.1.6192.40777
* Performed step 1 at https://www.microsoft.com/net/core#linuxubuntu to point to the dotnet distributions
* Performed `apt-get install dotnet-dev-1.0.0-preview3-004056` to get the version nswag claimed it wanted

So at this point I'm thinking everything should work, but:
```
cd /tmp
nswag new
# edit nswag.json and specify "client.js" for the `output` parameter in the `swaggerToTypeScriptClient` section
nswag run nswag.json
```
Get this output (preceded by standard header, and followed by additional stack detail - let me know if you need it):
```
Executing file 'nswag.json'...
System.AggregateException: One or more errors occurred. (Invalid URI: The format of the URI could not be determined.) ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at NSwag.CodeGeneration.Utilities.PathUtilities.MakeAbsolutePath(String relativePath, String relativeTo)
   at NSwag.CodeGeneration.NSwagDocument.GetDocumentDirectory()
   at NSwag.CodeGeneration.NSwagDocument.ConvertToAbsolutePath(String pathToConvert)
   at NSwag.Commands.NSwagDocumentBase.ConvertToAbsolutePaths()
   at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass26_0`1.<<LoadAsync>b__0>d.MoveNext()
```

I try it without a run file: `nswag swagger2tsclient /input:swagger.json /output:client.js` and get different exception:

```
System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: type) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NJsonSchema.Infrastructure.DynamicApis.HttpGet(String url)
   at NSwag.Commands.Base.InputOutputCommandBase.get_InputSwaggerDocument()
   at NSwag.Commands.SwaggerToTypeScriptClientCommand.<RunAsync>b__73_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
(+ more stack trace)

Any hints as to what I'm missing?

Thanks

**Comment by rsuter** [comment] 2016-12-17 23:53
I only tested NSwag on Windows... I think this is a problem with a different path handling on ubuntu... I have to create a setup to reproduce and fix this...

**Comment by rsuter** [comment] 2016-12-21 00:09
Problem 1: NJsonSchema uses WebClient to download files: 

![image](https://cloud.githubusercontent.com/assets/2603405/21372820/f5d30806-c719-11e6-9180-bb2f633ef067.png)

Must be changed to HttpClient which is available in .NET Core

Problem 2: MakeAbsolutePath does not work... I think this is because GetCurrentDirectory returns an unexpected path: 

![image](https://cloud.githubusercontent.com/assets/2603405/21372849/1c47898a-c71a-11e6-9217-3bec2efe0d23.png)

![image](https://cloud.githubusercontent.com/assets/2603405/21372851/233b1112-c71a-11e6-831b-435d5a874f90.png)

**Comment by rsuter** [comment] 2016-12-23 16:29
First problem should be fixed with: https://github.com/NSwag/NSwag/commit/5288da3d3585c2431463c99b75bde03de99b123b

Second problem should be fixed with the change to use HttpClient: https://github.com/NJsonSchema/NJsonSchema/commit/10fdfc13cdb4d996d785fe98fbb924cbbe32cb62#diff-4c9393cf46039236328d8f1f7c285ab9

**Comment by rsuter** [comment] 2016-12-23 18:58
With v8.2 I can create a new nswag file, and generate code from the petstore URL... so both problems are fixed.

**Closed by rsuter** 2016-12-23 18:58 UTC
Labels: bug

**Comment by andylowry** [comment] 2016-12-27 16:00
Thanks @rsuter. I am now able to execute nswag successfully on Ubuntu.
