### ISSUE TITLE
List<T> parameter to WebAPI action shows up as ObservableCollection<object> in generated client

### ISSUE THREAD

**Issue by gingacodeninja** [NSwag/NSwag#202] opened 2016-07-13 15:00 UTC
Given the following WebAPI action

    [ResponseType(typeof(List<int>))]
    [Route("Report/{ids}/{from}/{to}")]
    public IHttpActionResult Get(List<int> ids, DateTime from, DateTime to)
    {
        return Ok(ids);
    }

When you generate a client with swagger2csclient the parameter of type `List<int>` is converted to `ObservableCollection<object>`

And the following code cannot compile 

    var result = client.GetAsync(new ObservableCollection<int>(new List<int> { 1, 2, 3 }), 
        new DateTime(2016, 6, 1), new DateTime(2016, 7, 1)).Result;

I have tried specifying the type in the route, e.g. `[Route("Report/{ids:List<int>}/{from}/{to}")]` but no change.

Any ideas?

**Comment by rsuter** [comment] 2016-07-13 15:21
What about:

    var result = client.GetAsync(new ObservableCollection<int>() { 1, 2, 3 }, 
        new DateTime(2016, 6, 1), new DateTime(2016, 7, 1)).Result;

You can also change the array type to list (ArrayType property on settings)

**Comment by rsuter** [comment] 2016-07-13 15:22
... but yes, the array operation parameters should always be of type IEnumerable<...>

**Comment by gingacodeninja** [comment] 2016-07-13 15:24
That example doesn't work either because the generated client is expecting ObservableCollection<object> even though the actual WebAPI parameter is List<int>.

I've changed the ArrayType to "List" but it still loses the T type and converts to List<object> instead. Maybe the current code doesn't support generics?

**Comment by rsuter** [comment] 2016-07-13 15:32
The swagger spec only knows array and the generator uses the type from the settings to generate the .NET type... I think the problem is, that the currently generated code does not support path parameters of type array/list. Can you post the generated GetAsync method?

**Comment by rsuter** [comment] 2016-07-13 21:24
Fixed in https://github.com/NSwag/NSwag/commit/995c20fccd866bb95f49ff9ae53aabe07c0b2cde, NuGet v3.23, please reopen if not solved...

**Closed by rsuter** 2016-07-13 21:24 UTC
Labels: bug
