### ISSUE TITLE
WebAPI server code generation from JSON Schema or Swagger JSON

### ISSUE THREAD

**Issue by dockstreet** [NSwag/NSwag#16] opened 2015-12-16 16:20 UTC
First, the client code generator is awesome thanks for that!

Are there any plans in motion to create a WebAPI controller server generator ? 

Similar to what swagger-codegen provides for JAX-RS on the JAVA side?

**Comment by rsuter** [comment] 2015-12-16 19:01
So you want tools to generate Web API controllers from a Swagger specification?

**Comment by dockstreet** [comment] 2015-12-16 20:29
Yep , exactly - that would be great! 

Kind of like how WSCF.blue would do it for XML/SOAP ; but instead with Swagger / JSON schemas . 

https://wscfblue.codeplex.com/

**Comment by rsuter** [comment] 2015-12-16 21:13
This feature is currently not planned, but it should be simple to implement... We just have to implement another template and add a setting to choose it: 

https://github.com/NSwag/NSwag/tree/master/src/NSwag.CodeGeneration/ClientGenerators/CSharp/Templates

**Comment by dockstreet** [comment] 2015-12-17 00:13
Great to hear thanks!

**Comment by chadboyer** [comment] 2016-01-25 22:35
With the increasing movement to the "top-down" api design approach this would be an awesome addition.

**Comment by rsuter** [comment] 2016-01-26 08:47
How would the output look like? Abstract controller classes where the dev has to implement all abstract methods? This way the abstract classes can be regenerated and replaced without problems?

**Comment by chadboyer** [comment] 2016-01-26 13:07
I guess it could be solved a couple different ways.  Not knowing how the
various code reflecting tools work, it might not work to add the various
web api attributes to the abstract base class.   Maybe the safest bet would
be to create a class that either gets its implementation via DI or just
invokes the members in the base class. - you could put the implementation
in your base controller.

Anything you come up with would be an amazing addition to an already
awesome project.  Btw - nice work!!!

**Comment by rsuter** [comment] 2016-01-26 20:07
I just tried the abstract class idea, and it should work... I think generating abstract classes is better because with these classes, you don't need to use a DI framework. If you want to use DI, you can still do it in the controller implementation...

**Comment by artuj** [comment] 2016-01-29 00:53
Abstract classes will work, but you'll lose all annotations so you won't be able to regenerate swagger back again from generated code. Annotations for methods are not inherited in that case, they will be overridden by implementation.

The way it will work is to use DI as was mentioned before by chadboyer, ang generate both controllers (with annotations) and interfaces. Controllers in that case should be a proxy, invoking methods to injected depency implementing interface.

I have working solution based on that technique. Now I can switch between swagger-first and api-first approach anytime. Because project is written for my employer I can't share the code, but I can help to write something even better. Just let me know.

**Comment by rsuter** [comment] 2016-01-29 08:29
Ok, I think we should go with the DI/proxy solution... Makes sense. So you already implemented this with NSwag?

**Comment by artuj** [comment] 2016-01-29 10:58
I found NSwag just yesterday, but i really like the way it solves the problem. Till now I was using [https://github.com/domaindrivendev/Swashbuckle](url) with its annotations. For some reason, Swashbuckle uses mix of annotations and documentation comments (there is for sure no way to inherit them) to generate swagger json.

Since there is VS Comunity I think that next bigh thing would be making a VS Extension to provide full end-to-end solution to play with Swagger in a few clicks.

I need few days to study what you already did and we can get things started.

**Comment by rsuter** [comment] 2016-01-29 19:40
Experimental controller generator is live... But some features are missing/not ready yet (parameter attributes, poco generation, some edge cases). Please check if the headed direction is correct...

**Comment by rsuter** [comment] 2016-01-29 19:43
@artuj help is really appreciated. How do you want to help? Of course ill merge PRs...

**Comment by rsuter** [comment] 2016-01-29 19:46
A VS extension would be cool, and is surely doable. However, I currently do not have the time to implement this and VS integration is also possible with T4 templates or the cmd line tool (see wiki)

**Comment by artuj** [comment] 2016-01-30 11:09
I can handle VS Extension to make it more accessible to non experienced users. I will return in monday with little example, then will be ablle to discuss the next steps and requirements.

Below is a little example how I manage controller and interface generation. Annotations are Swashbuckle specific. As you can see, there are also comments. To make that work (to see them in generated swagger) you have to enable XML documentation file.

**Interface**
```c#
using IO.Swagger.Model;
using IO.Swagger.Responses;

namespace IO.Swagger.Interfaces
{
    public interface IClient
    {
        SendEmailResponse sendEmail(string clientId, EmailMessage emailMessage, string attachment);
    }
}
```

**Model**
```c#
using System.Runtime.Serialization;

namespace IO.Swagger.Model
{

    [DataContract]
    public class EmailMessage
    {

        [DataMember(Name = "emailid"]
        public string emailId { get; set; }


        [DataMember(Name = "datesent"]
        public string dateSent { get; set; }


        [DataMember(Name = "emailattachment"]
        public string emailAttachment { get; set; }


        [DataMember(Name = "emailmessage"]
        public string emailMessage { get; set; }


        [DataMember(Name = "emailstatus"]
        public string emailStatus { get; set; }


        [DataMember(Name = "emailsubject"]
        public string emailSubject { get; set; }
    }
}
```

**Controller:**
```c#
using Swashbuckle.Swagger.Annotations;
using System.Net;
using System.Collections.Generic;
using IO.Swagger.Model;
using System.Web.Http;
using IO.Swagger.Responses;
using IO.Swagger.Interfaces;

namespace IO.Swagger.Controllers
{
    [SwaggerResponse(HttpStatusCode.Unauthorized, Description = "Unauthorized", Type = typeof(List<Error>))]
    [SwaggerResponse(HttpStatusCode.BadRequest, Description = "Bad Request", Type = typeof(List<Error>))]
    [SwaggerResponse(HttpStatusCode.Forbidden, Description = "Forbidden", Type = typeof(List<Error>))]
    [SwaggerResponse(HttpStatusCode.InternalServerError, Description = "Internal Server Error", Type = typeof(List<Error>))]
    public class ClientController : ApiController
    {
        private IClient impl { get; set; }
        public ClientController(IClient impl)
        {
            this.impl = impl;
        }
        /// <summary>
        /// sends the email to the specified customer and returns the confirmation of the delivery
        /// </summary>
        /// <param name="clientId">The unique identifier of the client used in the core systems</param>
        /// <param name="emailMessage">the body of the email</param>
        /// <param name="attachment">the attachment  of the email</param>
        [SwaggerOperation(OperationId = "Client", Tags = new string[] { "Client", "#email", "#trusted_advice" })]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(SendEmailResponse))]
        [Route("client/{clientId}/email")]
        public SendEmailResponse sendEmail([FromUri]string clientId, [FromBody]EmailMessage emailMessage, string attachment)
        {
            return impl.sendEmail(clientId, emailMessage, attachment);
        }
    }
}


```

**Comment by alexanderkuznetsov96** [comment] 2016-08-04 21:25
Hey, 

what's the progress on this functionality? 

Cheers!

**Comment by rsuter** [comment] 2016-08-04 22:48
There is an experimental implementation (cmd line `swagger2cscontroller`)... try this and report any problems with it...

**Comment by rsuter** [comment] 2016-09-01 10:40
Can you post the full sample Swagger spec, so that i can create a unit test and fix this?

**Comment by andrewlock** [comment] 2016-09-01 10:53
Thanks for coming back so quickly, this reproduces the problem: 

```json
{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "Test Spec"
    },
    "host": "testendpoint",
    "schemes": [ "http" ],
    "paths": {
        "/location": {
            "get": {
                "tags": [ "Location" ],
                "operationId": "GetLocations",
                "consumes": [],
                "produces": [ "application/json", "text/json", "application/xml", "text/xml" ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": { "$ref": "#/definitions/Result[ICollection[LocationResult]]" }
                    }
                },
                "deprecated": false
            }
        }
    },
    "definitions": {
        "Object": {
            "type": "object",
            "properties": {}
        },
        "Result[ICollection[LocationResult]]": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/LocationResult" }
                },
                "message": { "type": "string" },
                "modelState": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": { "type": "string" }
                    },
                    "readOnly": true
                }
            }
        },
        "LocationResult": {
            "type": "object",
            "properties": {
                "id": {
                    "format": "int32",
                    "type": "integer"
                },
                "locationName": { "type": "string" },
                "ipAddresses": {
                    "type": "array",
                    "items": { "type": "string" }
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyToken": {
            "type": "apiKey",
            "description": "API Key Bearer Authentication e.g. Bearer thisisatestkey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [ { "APIKeyToken": [] } ]
}
```

Which generates this interface: 

```c#
[GeneratedCode("NSwag", "5.3.6085.39202")]
public interface ITestApiServerController
{
    /// <returns>OK</returns>
    Task<ResultOfICollection[LocationResult]> GetLocationsAsync();
    
}
```

and this result object:

```c#
[JsonObject(MemberSerialization.OptIn)]
[GeneratedCode("NJsonSchema", "4.2.6085.38782")]
public partial class ResultOfICollection[LocationResult] 
{
    
    [JsonProperty("value", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public List<LocationResult> Value { get; set; }
    
    [JsonProperty("message", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public string Message { get; set; }
    
    [JsonProperty("modelState", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public Dictionary<string, List<string>> ModelState { get; set; }
    
    public string ToJson() 
    {
        return JsonConvert.SerializeObject(this);
    }
        
    public static ResultOfICollection[LocationResult] FromJson(string data)
    {
        return JsonConvert.DeserializeObject<ResultOfICollection[LocationResult]>(data);
    }
}
```

**Comment by rsuter** [comment] 2016-09-01 11:10
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/9a6387154a128b0ae7ed307766433f9aa350fc2a

**Comment by andrewlock** [comment] 2016-09-01 11:18
That's brilliant, thanks:) 

I'm using the command line tooling (via chocolatey)  - any time frame for when I could update with the fix?

Really appreciate your speed on this!

**Comment by rsuter** [comment] 2016-09-01 11:38
I have to release NJsonSchema and then NSwag. I think in the next 2-3 days...

**Comment by andrewlock** [comment] 2016-09-01 11:48
Perfect, thanks again:)

**Comment by rsuter** [comment] 2016-10-03 23:43
Can we close this and add specific issues if needed?

**Comment by andrewlock** [comment] 2016-10-06 19:43
Fine by me

**Closed** 2016-10-06 19:47 UTC
Labels: csharp, enhancement
